# Generated by Django 2.1.3 on 2018-11-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20180630_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=500)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_content', models.TextField()),
                ('post_pictures', models.TextField()),
            ],
        ),
    ]
